version: '3.8'

services:
  bot:
    build: .
    container_name: name_change_bot
    volumes:
      - ./data:/app/data:rw
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 