version: '3.8'

services:
  bot:
    build: .
    container_name: name_change_bot
    volumes:
      - ./data:/app/data
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
    restart: unless-stopped 